    ###
    # Unload the KoNLP package
    detach("package:KoNLP", unload = TRUE)

    # Restart R session to ensure all dependencies are unloaded
    .rs.restartR()

    # Reinstall KoNLP from GitHub
    remotes::install_github('haven-jeon/KoNLP', upgrade = "never", force = TRUE)

    Sys.setenv(JAVA_HOME = "C:/Program Files/Java/jdk-11.0.10")

    # Install MeCab using KoNLP (may require administrator privileges)
    KoNLP::install_mecab("C:/mecab")

    # Load the KoNLP package
    library(KoNLP)

    # Use the Sejong dictionary
    useSejongDic()


    # Ensure the 'here' package is installed and loaded
    library(here)

    # Correctly read the file
    raw_moon <- readLines(here("Data", "speech_moon.txt"), encoding = "UTF-8")
    Sys.getenv("JAVA_HOME")
    Sys.setenv(JAVA_HOME = "C:/Program Files/Java/jdk-11.0.10")
    remove.packages("rJava")
    install.packages("rJava")
    library(rJava)
    .jinit()


    remotes::install_github('haven-jeon/KoNLP', upgrade = "never", force = TRUE)

    Sys.getenv("JAVA_HOME")
    Sys.setenv(JAVA_HOME = "C:/Program Files/Amazon Corretto/jdk11.0.20_9")
    remove.packages("rJava")
    install.packages("rJava")
    library(rJava)
    .jinit()
    remove.packages("KoNLP")
    install.packages("remotes")

    remotes::install_github('haven-jeon/KoNLP', upgrade = "never")

    options(download.file.method = "libcurl")

    remotes::install_github('haven-jeon/KoNLP', upgrade = "never", force = TRUE)

    library(KoNLP)
    useSejongDic()
    extractNoun("대한민국의 주권은 국민에게 있다.")


    options(download.file.method = "libcurl")
    install.packages("remotes")
    library(remotes)
    remotes::install_github('haven-jeon/KoNLP', upgrade = "never", force = TRUE)

    library(KoNLP)
    useSejongDic()
    extractNoun("한국어 형태소 분석을 테스트합니다.")
    ```

```{r}
Sys.setenv(JAVA_HOME = "C:/Program Files/Java/jdk1.8.0_202")
Sys.getenv("JAVA_HOME")

library(multilinguer)
remotes::install_github("haven-jeon/KoNLP",
                        upgrade = "never",
                        INSTALL_opts = c("--no-multiarch"))

remotes::install_github("haven-jeon/KoNLP", lib = "C:/R/library", upgrade = "never", INSTALL_opts = c("--no-multiarch"), force = TRUE)

.libPaths("C:/R/library")
Sys.setenv(JAVA_HOME = "C:/Program Files/Java/jdk1.8.0_202")
Sys.getenv("JAVA_HOME")
library(KoNLP)
useNIADic()

library(KoNLP)
library(dplyr)
text <- tibble(
  value = c("대한민국은 민주공화국이다.", 
            "대한민국의 주권은 국민에게 이쏙, 모든 권력은 국민으로부터 나온다.")
)

text
install.packages("tidytext")
library(tidytext)

text %>% 
  unnest_token(input = value,
               output = word, 
               token = extrtactNoun)
raw_moon <- readLines("sppech_moon.text", encoding = "UTF-8")

library(stringr)
library(textclean)

moon <- raw_moon %>% 
  str_replace_all("[^가-힣]", " ") %>% 
  str_squish() %>% 
  as_tibble()

word_noun <- moon %>% 
  unnest_tokens(input = value,
                output = word,
                token = extractNoun)

word_non <- word_non %>% 
  count(word, sort = T) %>% 
  filter(str_count(word) >1 )

word_noun
```
